BucketFull: "§a[动作提示] §b您的桶现在被装满了,小心使用哦!"
BucketFinish: "§a[动作提示] §b您的桶已经被用空了，要小心谨慎哦！"
ItemBreak: "§a[动作提示] §e您手上的工具耐久度已经被消耗完了哦~"
LevelChange: "§a[动作提示] §e您的等级成功变为了 "
Fish: "§a[动作提示] §b您在钓鱼，要认真要有耐心哦~"
Respawn: "§a[动作提示] §b您已经重生，下次要注意哦!"
Enchat: "§a[动作提示] §d您成功的附魔了该物品"
Ronglu: "§a[动作提示] §b您成功的从熔炉中取走了燃烧成功的物品"
SignChange: "§a[动作提示] §b您成功的设置好了一个牌子"