#感谢使用ActionAssistant 插件，各位的支持就是我的动力！
#下面是动作事件提示的信息，可修改

BucketFull: "§a[动作提示] §b您的水桶现在被装满了,小心使用哦!"
BucketFinish: "§a[动作提示] §b您的桶已经被用空了，要小心谨慎哦！"
ItemBreak: "§a[动作提示] §e您手上的工具耐久度已经被消耗完了哦~"
LevelChange: "§a[动作提示] §e您的等级成功变为了 "
Fish: "§a[动作提示] §b您在钓鱼，要认真要有耐心哦~"
Respawn: "§a[动作提示] §b您已经重生，下次要注意哦!"
Enchat: "§a[动作提示] §d您成功的附魔了该物品"
Ronglu: "§a[动作提示] §b您成功的从熔炉中取走了燃烧成功的物品"
SignChange: "§a[动作提示] §b您成功的设置好了一个牌子"

#下面是动作助手提示部分，可修改
Command: 
  Permission: "§c您没有权限来执行这个命令!"
  Bloodself: "§a[动作助手] §b您已经成功的为自己加满了血"
  PlayerNotOnline: "§a[动作助手] §c您输入的玩家不在线!"
  BloodFinish: "§a[动作助手] §e您的血量已经成功恢复为满值"
  WalkSpeed: "§a[动作助手] §c请输入正确的行走速度，速度值范围: §6-1 到 1"
  FlySpeed: "§a[动作助手] §c请输入正确的飞行速度，速度值范围: §6-1 到 1"
  WalkMessage: "§a[动作助手] §b您成功修改了您的行走速度"
  FlyMessage: "§a[动作助手] §b您成功修改了您的飞行速度"